#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

php artisan config:clear
php artisan config:cache

if [ "$ENV_TYPE" = "WEB" ];  then

#Clear Caches
php artisan view:clear
php artisan route:clear

#Setup Caches
php artisan view:cache
php artisan route:cache

fi

exec "$@"
