version: "3.3"
services:
    app_php:
        build:
            dockerfile: ./docker/php/Dockerfile
        environment:
            PHP_EXTENSION_XDEBUG_MODE: 'debug'
        volumes:
            - .:/var/www
        depends_on:
            - app_redis
            - app_db
        networks:
            - frontend
            - backend

    app_nginx:
        build:
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            -   target: 80
                published: 80
                protocol: tcp
                mode: host
            -   target: 3000
                published: 3000
                protocol: tcp
                mode: host
        volumes:
            - .:/var/www
        depends_on:
            - app_php
        networks:
            - frontend

    app_db:
        image: mysql:8.0.33
        restart: unless-stopped
        volumes:
            - ./storage/db_data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/my.cnf
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=merlin
            - MYSQL_DATABASE=course
        networks:
            - backend

    app_redis:
        image: redis:7.0.2-bullseye
        ports:
            - "6379:6379"
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment:
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
        networks:
            - backend
        depends_on:
            - app_db

    rundeck:
        image: rundeck/rundeck:4.15.0
        volumes:
            - rundeck:/home/rundeck/server/data
#            - rundeck:/home/rundeck/server/data
#            - rundeck-server-config:/home/rundeck/server/config
#            - rundeck-projects:/home/rundeck/projects
#            - rundeck-config:/home/rundeck/etc
        environment:
            - RUNDECK_GRAILS_URL=http://localhost:4440
            - RUNDECK_LOGGING_AUDIT_ENABLED=0
        networks:
            - backend
        depends_on:
            - app_db
        ports:
            - target: 4440
              published: 4440
              protocol: tcp
              mode: host
volumes:
    app_db:
    rundeck:
networks:
    frontend:
    backend:
