version: "3.3"
services:
    app_php:
        build:
            dockerfile: ./docker/php/Dockerfile
        environment:
            PHP_EXTENSION_XDEBUG_MODE: 'debug'
        volumes:
            - .:/var/www
        depends_on:
            - app_redis
            - app_db
        networks:
            - frontend
            - backend

    app_nginx:
        build:
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            -   target: 80
                published: 80
                protocol: tcp
                mode: host
            -   target: 3000
                published: 3000
                protocol: tcp
                mode: host
        volumes:
            - .:/var/www
        depends_on:
            - app_php
        networks:
            - frontend

    app_db:
        image: mysql:8.0.33
        restart: unless-stopped
        volumes:
            - ./storage/db_data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/my.cnf
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=admin
            - MYSQL_DATABASE=course
            - MYSQL_PASSWORD=root
        networks:
            - backend

    app_redis:
        image: redis:7.0.2-bullseye
        ports:
            - "6379:6379"
        networks:
            - backend

networks:
    frontend:
    backend:
